//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace batman_quiz_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quiz_singletable
    {
        public int question_id { get; set; }
        public string question_text { get; set; }
        public string question_answer1 { get; set; }
        public string question_answer2 { get; set; }
        public string question_answer3 { get; set; }
        public string question_answer4 { get; set; }
        public string question_rightanswer { get; set; }
    }
}
